/**
 * Volcengine's system voices, per resource.
 *
 * Volcengine has no public API that lists voices, so this table is a snapshot
 * of the console's own voice library (`ListSpeakers`, version 2025-05-20, taken
 * 2026-09-30): every voice there was `online`. Regenerate it the same way when
 * the library changes; a voice missing here can still be typed into the voice
 * picker by id.
 *
 * One 1.0 voice id can appear in the console under several personas (灿灿 and
 * "Shiny" are the same `zh_female_cancan_mars_bigtts`), so ids are merged and
 * their names joined. `lang` is the persona's language as BCP-47 (English split
 * by the console's 美式/英式/澳洲 labels); a voice whose personas speak
 * different languages, and none of them Chinese, has no `lang`. The first entry of each list is
 * the adapter's default voice.
 *
 * Loaded only by `listVoices()`, so the offscreen document never pays for it.
 */
import type { Voice } from './types';

/** Voices the `seed-tts-1.0` resource accepts. */
export const VOICES_1_0: readonly Voice[] = [
  {
    id: 'zh_female_shuangkuaisisi_moon_bigtts',
    name: '爽快思思 / Skye',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_junlangnanyou_emo_v2_mars_bigtts',
    name: '俊朗男友',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_female_shaoergushi_mars_bigtts', name: '少儿故事', lang: 'zh-CN', gender: 'female' },
  {
    id: 'multi_female_maomao_conversation_wvae_bigtts',
    name: 'Diana / つき（月）',
    gender: 'female',
  },
  { id: 'multi_male_M100_conversation_wvae_bigtts', name: 'Lucía', lang: 'es-MX', gender: 'male' },
  {
    id: 'multi_female_sophie_conversation_wvae_bigtts',
    name: 'Sofía / さとみ（智美）',
    gender: 'female',
  },
  {
    id: 'multi_male_xudong_conversation_wvae_bigtts',
    name: 'Daníel / まさお（正男）',
    gender: 'male',
  },
  {
    id: 'multi_male_jingqiangkanye_moon_bigtts',
    name: 'Javier or Álvaro / かずね（和音）',
    gender: 'male',
  },
  {
    id: 'multi_female_shuangkuaisisi_moon_bigtts',
    name: 'Esmeralda / はるこ（晴子）',
    gender: 'female',
  },
  { id: 'multi_male_wanqudashu_moon_bigtts', name: 'Roberto / ひろし（広志）', gender: 'male' },
  { id: 'zh_male_shenyeboke_emo_v2_mars_bigtts', name: '深夜播客', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_jitangmeimei_mars_bigtts',
    name: '鸡汤妹妹 / Hope',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_jingqiangkanye_moon_bigtts',
    name: '京腔侃爷 / Harmony',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_male_shaonianzixin_moon_bigtts',
    name: '少年梓辛 / Brayan',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_male_wennuanahu_moon_bigtts', name: '温暖阿虎 / Alvin', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_wenroushunv_mars_bigtts', name: '温柔淑女', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_qingcang_mars_bigtts', name: '擎苍', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_baqiqingshu_mars_bigtts', name: '霸气青叔', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_ruyaqingnian_mars_bigtts', name: '儒雅青年', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_changtianyi_mars_bigtts', name: '悬疑解说', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_silang_mars_bigtts', name: '四郎', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_chunhui_mars_bigtts', name: '广告解说', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_yingtaowanzi_mars_bigtts', name: '樱桃丸子', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_gujie_mars_bigtts', name: '顾姐', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_wuzetian_mars_bigtts', name: '武则天', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_peiqi_mars_bigtts', name: '佩奇猪', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_xionger_mars_bigtts', name: '熊二', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_wenrouxiaoya_moon_bigtts', name: '温柔小雅', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_maomao_conversation_wvae_bigtts',
    name: '文静毛毛',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_xudong_conversation_wvae_bigtts',
    name: '快乐小东 / Daniel',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_male_M100_conversation_wvae_bigtts',
    name: '悠悠君子 / Lucas',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_male_dongfanghaoran_moon_bigtts', name: '东方浩然', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_yuanqinvyou_moon_bigtts', name: '撒娇学妹', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_sajiaonvyou_moon_bigtts', name: '柔美女友', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_shenyeboke_moon_bigtts', name: '深夜播客', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_meilinvyou_moon_bigtts', name: '魅力女友', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_aojiaobazong_moon_bigtts', name: '傲娇霸总', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_gaolengyujie_moon_bigtts', name: '高冷御姐', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_popo_mars_bigtts', name: '婆婆', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_naiqimengwa_mars_bigtts', name: '奶气萌娃', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_meituojieer_moon_bigtts', name: '妹坨洁儿', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_beijingxiaoye_moon_bigtts', name: '北京小爷', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_haoyuxiaoge_moon_bigtts', name: '浩宇小哥', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_guozhoudege_moon_bigtts', name: '广州德哥', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_wanqudashu_moon_bigtts', name: '湾区大叔', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_wanwanxiaohe_moon_bigtts', name: '湾湾小何', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_male_zhoujielun_emo_v2_mars_bigtts',
    name: '双节棍小哥',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_male_guangxiyuanzhou_moon_bigtts', name: '广西远舟', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_daimengchuanmei_moon_bigtts',
    name: '呆萌川妹',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_yuzhouzixuan_moon_bigtts', name: '豫州子轩', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_xinlingjitang_moon_bigtts', name: '心灵鸡汤', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_tianmeiyueyue_moon_bigtts', name: '甜美悦悦', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_linjiananhai_moon_bigtts', name: '邻家男孩', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_kailangjiejie_moon_bigtts', name: '开朗姐姐', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_jieshuoxiaoming_moon_bigtts', name: '解说小明', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_qingchezizi_moon_bigtts', name: '清澈梓梓', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_tianmeixiaoyuan_moon_bigtts',
    name: '甜美小源',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_yangguangqingnian_moon_bigtts', name: '阳光青年', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_yuanboxiaoshu_moon_bigtts', name: '渊博小叔', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_linjianvhai_moon_bigtts', name: '邻家女孩', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_qingshuangnanda_mars_bigtts', name: '清爽男大', lang: 'zh-CN', gender: 'male' },
  { id: 'en_male_jason_conversation_wvae_bigtts', name: '开朗学长', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_qinqienvsheng_moon_bigtts', name: '亲切女声', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_ruyayichen_emo_v2_mars_bigtts', name: '儒雅男友', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_male_yourougongzi_emo_v2_mars_bigtts',
    name: '优柔公子',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_female_linjuayi_emo_v2_mars_bigtts',
    name: '邻居阿姨',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_jingqiangkanye_emo_mars_bigtts', name: '京腔侃爷', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_guangzhoudege_emo_mars_bigtts', name: '广州德哥', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_tianxinxiaomei_emo_v2_mars_bigtts',
    name: '甜心小美',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_beijingxiaoye_emo_v2_mars_bigtts',
    name: '北京小爷',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_female_yueyunv_mars_bigtts', name: '粤语小溏', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_lengkugege_emo_v2_mars_bigtts', name: '冷酷哥哥', lang: 'zh-CN', gender: 'male' },
  { id: 'en_female_candice_emo_v2_mars_bigtts', name: 'Candice', lang: 'en-US', gender: 'female' },
  {
    id: 'zh_male_yangguangqingnian_emo_v2_mars_bigtts',
    name: '阳光青年',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_female_meilinvyou_emo_v2_mars_bigtts',
    name: '魅力女友',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'multi_female_gaolengyujie_moon_bigtts',
    name: 'あけみ（朱美）',
    lang: 'ja-JP',
    gender: 'female',
  },
  {
    id: 'multi_zh_male_youyoujunzi_moon_bigtts',
    name: 'ひかる（光）',
    lang: 'ja-JP',
    gender: 'male',
  },
  { id: 'zh_female_qingxinnvsheng_mars_bigtts', name: '清新女声', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_shuangkuaisisi_emo_v2_mars_bigtts',
    name: '爽快思思',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_roumeinvyou_emo_v2_mars_bigtts',
    name: '柔美女友',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_female_yingyujiaoyu_mars_bigtts', name: 'Tina老师', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_fanjuanqingnian_mars_bigtts', name: '反卷青年', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_gufengshaoyu_mars_bigtts', name: '古风少御', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_yangguangqingnian_mars_bigtts', name: '活力小哥', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_mengyatou_mars_bigtts',
    name: '萌丫头 / Cutey',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_tiexinnvsheng_mars_bigtts',
    name: '贴心女声 / Candy',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_dongmanhaimian_mars_bigtts', name: '亮嗓萌仔', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_lanxiaoyang_mars_bigtts', name: '懒音绵宝', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_qiaopinvsheng_mars_bigtts', name: '俏皮女声', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_sunwukong_mars_bigtts', name: '猴哥', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_tiancaitongsheng_mars_bigtts', name: '天才童声', lang: 'zh-CN', gender: 'male' },
  { id: 'en_male_dryw_mars_bigtts', name: 'Dryw', lang: 'en-AU', gender: 'male' },
  { id: 'en_female_sarah_mars_bigtts', name: 'Sarah', lang: 'en-AU', gender: 'female' },
  { id: 'en_female_anna_mars_bigtts', name: 'Anna', lang: 'en-GB', gender: 'female' },
  { id: 'en_male_smith_mars_bigtts', name: 'Smith', lang: 'en-GB', gender: 'male' },
  { id: 'en_male_jackson_mars_bigtts', name: 'Jackson', lang: 'en-US', gender: 'male' },
  { id: 'en_female_amanda_mars_bigtts', name: 'Amanda', lang: 'en-US', gender: 'female' },
  { id: 'en_male_adam_mars_bigtts', name: 'Adam', lang: 'en-US', gender: 'male' },
  { id: 'zh_female_cancan_mars_bigtts', name: '灿灿 / Shiny', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_wenrouxiaoge_mars_bigtts', name: '温柔小哥', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_zhixingnvsheng_mars_bigtts', name: '知性女声', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_tianmeitaozi_mars_bigtts', name: '甜美桃子', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_qingyiyuxuan_mars_bigtts', name: '阳光阿辰', lang: 'zh-CN', gender: 'male' },
];

/** Voices the `seed-tts-2.0` resource accepts. */
export const VOICES_2_0: readonly Voice[] = [
  { id: 'zh_female_vv_uranus_bigtts', name: 'Vivi 2.0', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_xiaohe_uranus_bigtts', name: '小何 2.0', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_wennuanahu_uranus_bigtts', name: '温暖阿虎 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_male_jieshuoxiaoming_uranus_bigtts',
    name: '解说小明 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_female_wenroumama_uranus_bigtts',
    name: '温柔妈妈 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_female_sophie_uranus_bigtts', name: '魅力苏菲 2.0 ', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_meilinvyou_uranus_bigtts',
    name: '魅力女友 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_liufei_uranus_bigtts', name: '刘飞 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_male_shaonianzixin_uranus_bigtts',
    name: '少年梓辛 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_male_taocheng_uranus_bigtts', name: '小天 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_m191_uranus_bigtts', name: '云舟 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_male_guanggaojieshuo_uranus_bigtts',
    name: '广告解说 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_female_gujie_uranus_bigtts', name: '顾姐 2.0', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_wuzetian_uranus_bigtts', name: '武则天 2.0', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_peiqi_uranus_bigtts', name: '佩奇猪 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_male_qingshuangnanda_uranus_bigtts',
    name: '清爽男大 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_female_kefuwanjun_tob',
    name: '客服婉君 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_tiexinnvsheng_uranus_bigtts',
    name: '贴心女声 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_jitangmei_uranus_bigtts',
    name: '鸡汤妹妹 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_cixingjieshuonan_uranus_bigtts',
    name: '磁性解说男声 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_female_mengyatou_uranus_bigtts', name: '萌丫头 2.0', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_qiaopinv_uranus_bigtts', name: '俏皮女声 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_shaoergushi_uranus_bigtts',
    name: '少儿故事 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_tiancaitongsheng_uranus_bigtts',
    name: '天才童声 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_female_wenrouxiaoya_uranus_bigtts',
    name: '温柔小雅 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_dongfanghaoran_uranus_bigtts',
    name: '东方浩然 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_female_roumeinvyou_uranus_bigtts',
    name: '柔美女友 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_wenrouxiaoge_uranus_bigtts', name: '温柔小哥 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_xinlingjitang_uranus_bigtts',
    name: '心灵鸡汤 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_tianmeiyueyue_uranus_bigtts',
    name: '甜美悦悦 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_qingchezizi_uranus_bigtts',
    name: '清澈梓梓  2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_yangguangqingnian_uranus_bigtts',
    name: '阳光青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_male_yuanboxiaoshu_uranus_bigtts',
    name: '渊博小叔 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_female_zhixingnv_uranus_bigtts',
    name: '知性女声 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_wenjingmaomao_uranus_bigtts',
    name: '文静毛毛 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_youyoujunzi_uranus_bigtts', name: '悠悠君子 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_male_kailangxuezhang_uranus_bigtts',
    name: '开朗学长 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_male_kuailexiaodong_uranus_bigtts',
    name: '快乐小东 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_female_qinqienv_uranus_bigtts', name: '亲切女声 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_zhishuaiyingzi_uranus_bigtts',
    name: '直率英子 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_female_nvleishen_uranus_bigtts', name: '女雷神 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_chanmeinv_uranus_bigtts',
    name: '谄媚女声 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_ganmaodianyin_uranus_bigtts',
    name: '感冒电音姐姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_zhubajie_uranus_bigtts', name: '猪八戒 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_kailangdidi_uranus_bigtts', name: '开朗弟弟 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_zhuangzhou_uranus_bigtts', name: '庄周 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_tangseng_uranus_bigtts', name: '唐僧 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_chunribu_uranus_bigtts',
    name: '春日部姐姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_female_lingling_uranus_bigtts', name: '玲玲姐姐 2.0', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_female_linxiao_uranus_bigtts', name: '林潇 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_jiaochuannv_uranus_bigtts',
    name: '娇喘女声 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_lubanqihao_uranus_bigtts', name: '鲁班七号 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_shenyeboke_uranus_bigtts', name: '深夜播客 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_gaolengyujie_uranus_bigtts',
    name: '高冷御姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_kailangjiejie_uranus_bigtts',
    name: '开朗姐姐  2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_liangsangmengzai_uranus_bigtts',
    name: '亮嗓萌仔 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_male_xuanyijieshuo_uranus_bigtts',
    name: '悬疑解说 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_male_baqiqingshu_uranus_bigtts', name: '霸气青叔 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_huolixiaoge_uranus_bigtts', name: '活力小哥 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_gufengshaoyu_uranus_bigtts',
    name: '古风少御 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_wenroushunv_uranus_bigtts',
    name: '温柔淑女 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_male_fanjuanqingnian_uranus_bigtts',
    name: '反卷青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'zh_male_lanyinmianbao_uranus_bigtts',
    name: '懒音绵宝 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'zh_male_aojiaobazong_uranus_bigtts', name: '傲娇霸总 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_popo_uranus_bigtts', name: '婆婆 2.0', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_naiqimengwa_uranus_bigtts', name: '奶气萌娃 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_yingtaowanzi_uranus_bigtts',
    name: '樱桃丸子 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_xionger_uranus_bigtts', name: '熊二 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_qingcang_uranus_bigtts', name: '擎苍 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_ruyaqingnian_uranus_bigtts', name: '儒雅青年 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_silang_uranus_bigtts', name: '四郎 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_linjiananhai_uranus_bigtts', name: '邻家男孩 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_male_yizhipiannan_uranus_bigtts', name: '译制片男 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'zh_female_tvbnv_uranus_bigtts', name: 'TVB女声 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_sajiaoxuemei_uranus_bigtts',
    name: '撒娇学妹 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_linjianvhai_uranus_bigtts',
    name: '邻家女孩 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_kefunvsheng_uranus_bigtts',
    name: '暖阳女声 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_female_cancan_uranus_bigtts', name: '知性灿灿 2.0', lang: 'zh-CN', gender: 'female' },
  { id: 'zh_male_ruyayichen_uranus_bigtts', name: '儒雅逸辰 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_liuchangnv_uranus_bigtts',
    name: '流畅女声 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_female_jitangnv_uranus_bigtts', name: '鸡汤女 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_mizai_uranus_bigtts',
    name: '黑猫侦探社咪仔 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_dayi_uranus_bigtts', name: '大壹 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_yingyujiaoxue_uranus_bigtts',
    name: 'Tina老师 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'zh_male_sunwukong_uranus_bigtts', name: '猴哥 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'zh_female_shuangkuaisisi_uranus_bigtts',
    name: '爽快思思 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_tianmeitaozi_uranus_bigtts',
    name: '甜美桃子 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'zh_female_qingxinnvsheng_uranus_bigtts',
    name: '清新女声 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_yingxiaokefu_v2_tob',
    name: '营销小楠 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_kefunvshengwenhecuishou_tob',
    name: '外呼凌凌 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'en_male_russell_uranus_bigtts', name: 'Russell', lang: 'en-GB', gender: 'male' },
  { id: 'en_male_knightley_uranus_bigtts', name: 'Knightley', lang: 'en-GB', gender: 'male' },
  {
    id: 'en_female_authoritative-british_uranus_bigtts',
    name: 'Charlotte',
    lang: 'en-GB',
    gender: 'female',
  },
  { id: 'en_male_father-christmas_uranus_bigtts', name: 'Alfred ', lang: 'en-GB', gender: 'male' },
  { id: 'es_male_guillem_uranus_bigtts', name: 'Guillem', lang: 'es-MX', gender: 'male' },
  { id: 'es_female_ht_mx_f6_uranus_bigtts', name: 'Marisol', lang: 'es-MX', gender: 'female' },
  {
    id: 'ICL_uranus_zh_male_zhengzhiqingnian_tob',
    name: '正直青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_youroubangzhu_tob',
    name: '优柔帮主 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_xiaosasuixing_tob',
    name: '潇洒随性 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_shuaizhenxiaohuo_tob',
    name: '率真小伙 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_sajiaonianren_tob',
    name: '撒娇粘人 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_ruyacaijun_tob', name: '儒雅才俊 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_qingsexiaosheng_tob',
    name: '青涩小生 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_nuanxintitie_tob',
    name: '暖心体贴 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_lvchaxiaoge_tob', name: '绿茶小哥 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_lengdanshuli_tob',
    name: '冷淡疏离 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_kailangqingkuai_tob',
    name: '开朗轻快 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_huoposhuanglang_tob',
    name: '活泼爽朗 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_hanhoudunshi_tob',
    name: '憨厚敦实 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_guzhibingjiao_tob',
    name: '固执病娇 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_guiyishenmi_tob', name: '诡异神秘 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'ICL_uranus_zh_male_fuheigongzi_tob', name: '腹黑公子 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_bingjiaobailian_tob',
    name: '病娇白莲 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_zhenbiandiyu_tob',
    name: '枕边低语 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_aoqilingren_tob', name: '傲气凌人 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_female_zhixingwenwan_tob',
    name: '知性温婉 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_wenrouwenya_tob',
    name: '温柔文雅 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_wenrounvshen_tob',
    name: '温柔女神 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_tianmeihuopo_tob',
    name: '甜美活泼 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_rouguhunshi_tob',
    name: '柔骨魂师 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_nuanxinxuejie_tob',
    name: '暖心学姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_keainvsheng_tob',
    name: '可爱女生 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_jiaohannvwang_tob',
    name: '娇憨女王 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_huopodiaoman_tob',
    name: '活泼刁蛮 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_chengshuwenrou_tob',
    name: '成熟温柔 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_bingjiaomengmei_tob',
    name: '病娇萌妹 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_aomanjiaosheng_tob',
    name: '傲慢娇声 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_tiaopigongzhu_tob',
    name: '调皮公主 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_en_male_big_boogie_tob',
    name: 'Big Boogie 2.0',
    lang: 'en-US',
    gender: 'male',
  },
  { id: 'ICL_uranus_en_male_michael_tob', name: 'Michael 2.0', lang: 'en-US', gender: 'male' },
  {
    id: 'ICL_uranus_en_male_kevin_mccallister_tob',
    name: 'Kevin McCallister 2.0',
    lang: 'en-US',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_en_male_the_grinch_tob',
    name: 'The Grinch 2.0',
    lang: 'en-US',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_en_male_frosty_man_tob',
    name: 'Frosty Man 2.0',
    lang: 'en-US',
    gender: 'male',
  },
  { id: 'th_female_bv568_fear_uranus_bigtts', name: 'Iris', lang: 'th-TH', gender: 'female' },
  { id: 'ru_female_sophie_uranus_bigtts', name: 'Ksenia', lang: 'ru-RU', gender: 'female' },
  { id: 'ru_female_af07_uranus_bigtts', name: 'Amelia', lang: 'ru-RU', gender: 'female' },
  { id: 'pt_male_bv531_uranus_bigtts', name: 'Arthur', lang: 'pt-BR', gender: 'male' },
  { id: 'mx_male_felipe_uranus_bigtts', name: 'Felipe', lang: 'es-MX', gender: 'male' },
  { id: 'mx_female_bv166emotion_uranus_bigtts', name: 'Rosa', lang: 'es-MX', gender: 'female' },
  { id: 'mx_female_bv065_uranus_bigtts', name: 'Irene', lang: 'es-MX', gender: 'female' },
  { id: 'ko_male_m03_uranus_bigtts', name: 'Minho', lang: 'ko-KR', gender: 'male' },
  { id: 'ko_male_bv545_uranus_bigtts', name: 'Jay', lang: 'ko-KR', gender: 'male' },
  { id: 'ja_female_bv024_uranus_bigtts', name: 'Bonnie', lang: 'ja-JP', gender: 'female' },
  { id: 'id_female_f20_uranus_bigtts', name: 'Chloe', lang: 'id-ID', gender: 'female' },
  { id: 'id_male_bv164dialogue_uranus_bigtts', name: 'Elian', lang: 'id-ID', gender: 'male' },
  { id: 'fr_male_usseau_uranus_bigtts', name: 'Usseau', lang: 'fr-FR', gender: 'male' },
  { id: 'es_male_dani_uranus_bigtts', name: 'Dani', lang: 'es-MX', gender: 'male' },
  { id: 'en_female_zendaya_p1_uranus_bigtts', name: 'Zendaya', lang: 'en-US', gender: 'female' },
  {
    id: 'en_female_wenrouzhishijieshuonv_uranus_bigtts',
    name: 'Megan',
    lang: 'en-US',
    gender: 'female',
  },
  { id: 'en_female_scarlet_p1_uranus_bigtts', name: 'Scarlet', lang: 'en-US', gender: 'female' },
  { id: 'en_male_ronald_uranus_bigtts', name: 'Ronald', lang: 'en-US', gender: 'male' },
  {
    id: 'en_male_michael_kevin_uranus_bigtts',
    name: 'Michael_Kevin',
    lang: 'en-US',
    gender: 'male',
  },
  { id: 'en_male_josh_coery_uranus_bigtts', name: 'Josiah', lang: 'en-US', gender: 'male' },
  { id: 'en_female_jane_uranus_bigtts', name: 'Jane', lang: 'en-US', gender: 'female' },
  { id: 'en_male_hades_uranus_bigtts', name: 'Beau', lang: 'en-US', gender: 'male' },
  { id: 'en_male_deep-voice_uranus_bigtts', name: 'Orion', lang: 'en-US', gender: 'male' },
  { id: 'en_male_alberto_uranus_bigtts', name: 'Alberto', lang: 'en-US', gender: 'male' },
  { id: 'ar_male_youssef_uranus_bigtts', name: 'Youssef', lang: 'ar', gender: 'male' },
  { id: 'ar_female_dina_uranus_bigtts', name: 'Dina', lang: 'ar', gender: 'female' },
  { id: 'en_male_marcus_uranus_bigtts', name: 'Marcus', lang: 'en-US', gender: 'male' },
  {
    id: 'zh_male_gaolengchenwen_uranus_bigtts',
    name: '高冷沉稳 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'it_male_enzo_uranus_bigtts', name: 'Enzo', lang: 'it-IT', gender: 'male' },
  { id: 'vi_male_wumg_uranus_bigtts', name: 'Wumg', lang: 'vi-VN', gender: 'male' },
  { id: 'vi_female_wu_uranus_bigtts', name: 'Wu', lang: 'vi-VN', gender: 'female' },
  { id: 'vi_female_ruan_uranus_bigtts', name: 'Ruan', lang: 'vi-VN', gender: 'female' },
  { id: 'vi_female_partner_uranus_bigtts', name: 'Partner', lang: 'vi-VN', gender: 'female' },
  { id: 'vi_female_linh_uranus_bigtts', name: 'Linh', lang: 'vi-VN', gender: 'female' },
  { id: 'vi_female_ling_uranus_bigtts', name: 'Ling', lang: 'vi-VN', gender: 'female' },
  { id: 'vi_female_hong_uranus_bigtts', name: 'Hong', lang: 'vi-VN', gender: 'female' },
  { id: 'tl_female_hervie_uranus_bigtts', name: 'Hervie', lang: 'fil-PH', gender: 'female' },
  { id: 'tl_male_ed_uranus_bigtts', name: 'Ed', lang: 'fil-PH', gender: 'male' },
  { id: 'tl_female_annika_uranus_bigtts', name: 'Annika', lang: 'fil-PH', gender: 'female' },
  { id: 'th_female_bv568_suprise_uranus_bigtts', name: 'Phoebe', lang: 'th-TH', gender: 'female' },
  { id: 'th_female_bv568_sad_uranus_bigtts', name: 'Lydia', lang: 'th-TH', gender: 'female' },
  { id: 'th_female_bv568_neutral_uranus_bigtts', name: 'Mildred', lang: 'th-TH', gender: 'female' },
  { id: 'th_female_bv568_hate_uranus_bigtts', name: 'Valentina', lang: 'th-TH', gender: 'female' },
  { id: 'th_female_bv568_happy_uranus_bigtts', name: 'Zara', lang: 'th-TH', gender: 'female' },
  { id: 'th_female_bv568_angry_uranus_bigtts', name: 'Valeria', lang: 'th-TH', gender: 'female' },
  { id: 'ru_male_vlad_uranus_bigtts', name: 'Silas', lang: 'ru-RU', gender: 'male' },
  { id: 'ru_male_pavel_uranus_bigtts', name: 'Pavel', lang: 'ru-RU', gender: 'male' },
  { id: 'ru_female_irinae_uranus_bigtts', name: 'Irinae', lang: 'ru-RU', gender: 'female' },
  { id: 'pt_male_rael_uranus_bigtts', name: 'Rael', lang: 'pt-BR', gender: 'male' },
  { id: 'pt_male_martins_uranus_bigtts', name: 'Toby', lang: 'pt-BR', gender: 'male' },
  { id: 'pt_female_mari_uranus_bigtts', name: 'Mari', lang: 'pt-BR', gender: 'female' },
  { id: 'pt_female_bv530_uranus_bigtts', name: 'Sofia', lang: 'pt-BR', gender: 'female' },
  { id: 'pt_female_bv173narrator_uranus_bigtts', name: 'Emma', lang: 'pt-BR', gender: 'female' },
  { id: 'pt_female_bv173emotion_uranus_bigtts', name: 'Lola', lang: 'pt-BR', gender: 'female' },
  { id: 'pt_female_bv173dialogue_uranus_bigtts', name: 'Elena', lang: 'pt-BR', gender: 'female' },
  { id: 'pt_female_bv173_uranus_bigtts', name: 'Diana', lang: 'pt-BR', gender: 'female' },
  { id: 'pt_male_bv172narrator_uranus_bigtts', name: 'Miles', lang: 'pt-BR', gender: 'male' },
  { id: 'pt_male_bv172emotion_uranus_bigtts', name: 'Vincent', lang: 'pt-BR', gender: 'male' },
  { id: 'pt_male_bv172dialogue_uranus_bigtts', name: 'Walter', lang: 'pt-BR', gender: 'male' },
  { id: 'pt_male_bv172_uranus_bigtts', name: 'Sam', lang: 'pt-BR', gender: 'male' },
  { id: 'mx_male_marcelo_uranus_bigtts', name: 'Marcelo', lang: 'es-MX', gender: 'male' },
  { id: 'mx_female_leslie_uranus_bigtts', name: 'Leslie', lang: 'es-MX', gender: 'female' },
  { id: 'mx_male_ht_mx_m012_uranus_bigtts', name: 'Derek', lang: 'es-MX', gender: 'male' },
  { id: 'mx_female_bv166narrator_uranus_bigtts', name: 'Freya', lang: 'es-MX', gender: 'female' },
  { id: 'mx_female_bv166dialogue_uranus_bigtts', name: 'Lucy', lang: 'es-MX', gender: 'female' },
  { id: 'mx_male_bv165narrator_uranus_bigtts', name: 'Marcos', lang: 'es-MX', gender: 'male' },
  { id: 'mx_male_bv165dialogue_uranus_bigtts', name: 'Diego', lang: 'es-MX', gender: 'male' },
  { id: 'ms_male_naim_uranus_bigtts', name: 'Naim', lang: 'ms-MY', gender: 'male' },
  { id: 'ms_male_ham_uranus_bigtts', name: 'Ham', lang: 'ms-MY', gender: 'male' },
  { id: 'ko_male_shane_uranus_bigtts', name: 'Shane', lang: 'ko-KR', gender: 'male' },
  { id: 'ko_female_bv546_uranus_bigtts', name: 'Momo', lang: 'ko-KR', gender: 'female' },
  { id: 'ja_female_shirou_uranus_bigtts', name: 'Shirou', lang: 'ja-JP', gender: 'female' },
  { id: 'ja_female_minimi_uranus_bigtts', name: 'Minimi', lang: 'ja-JP', gender: 'female' },
  { id: 'ja_male_bv524_uranus_bigtts', name: 'Ken', lang: 'ja-JP', gender: 'male' },
  { id: 'ja_female_bv523_uranus_bigtts', name: 'Lily', lang: 'ja-JP', gender: 'female' },
  { id: 'ja_female_bv522_uranus_bigtts', name: 'Hana', lang: 'ja-JP', gender: 'female' },
  { id: 'ja_female_bv521_uranus_bigtts', name: 'Aoi', lang: 'ja-JP', gender: 'female' },
  { id: 'ja_female_bv520_uranus_bigtts', name: 'Poppy', lang: 'ja-JP', gender: 'female' },
  { id: 'id_female_phulia_uranus_bigtts', name: 'Phulia', lang: 'id-ID', gender: 'female' },
  { id: 'id_male_m08_uranus_bigtts', name: 'Kyle', lang: 'id-ID', gender: 'male' },
  { id: 'id_male_han_uranus_bigtts', name: 'Han', lang: 'id-ID', gender: 'male' },
  { id: 'id_male_bv164narration_uranus_bigtts', name: 'Ronan', lang: 'id-ID', gender: 'male' },
  { id: 'id_female_bv164_uranus_bigtts', name: 'Crew', lang: 'id-ID', gender: 'female' },
  {
    id: 'id_female_bv161narration_uranus_bigtts',
    name: 'Celeste',
    lang: 'id-ID',
    gender: 'female',
  },
  { id: 'id_female_bv161dialogue_uranus_bigtts', name: 'Sylvia', lang: 'id-ID', gender: 'female' },
  { id: 'id_female_bv161_uranus_bigtts', name: 'Clara', lang: 'id-ID', gender: 'female' },
  { id: 'id_male_bv160narration_uranus_bigtts', name: 'Hugo', lang: 'id-ID', gender: 'male' },
  { id: 'id_male_bv160dialogue_uranus_bigtts', name: 'Jude', lang: 'id-ID', gender: 'male' },
  { id: 'id_male_bv160_uranus_bigtts', name: 'Rocco', lang: 'id-ID', gender: 'male' },
  { id: 'fr_male_fr_m29_uranus_bigtts', name: 'Maurice', lang: 'fr-FR', gender: 'male' },
  { id: 'fr_female_fr_f47_uranus_bigtts', name: 'Camille', lang: 'fr-FR', gender: 'female' },
  { id: 'fr_female_fr_bv078_uranus_bigtts', name: 'Simone', lang: 'fr-FR', gender: 'female' },
  { id: 'es_female_bv084_uranus_bigtts', name: 'Gracie', lang: 'es-MX', gender: 'female' },
  { id: 'en_male_yangguangjieshuonan_uranus_bigtts', name: 'Dylan', lang: 'en-US', gender: 'male' },
  { id: 'en_female_xinwenjieshuonv_uranus_bigtts', name: 'Kayla', lang: 'en-US', gender: 'female' },
  { id: 'en_male_valentino_corey_uranus_bigtts', name: 'Clark', lang: 'en-US', gender: 'male' },
  { id: 'en_male_valentino_uranus_bigtts', name: 'Valentino', lang: 'en-US', gender: 'male' },
  { id: 'en_male_tom_hiddleston_p1_uranus_bigtts', name: 'Tom', lang: 'en-US', gender: 'male' },
  { id: 'en_female_skye_uranus_bigtts', name: 'Skye', lang: 'en-US', gender: 'female' },
  { id: 'en_male_simba_p1_uranus_bigtts', name: 'Simba', lang: 'en-US', gender: 'male' },
  { id: 'en_female_sharron_uranus_bigtts', name: 'Sharron', lang: 'en-US', gender: 'female' },
  { id: 'en_female_rachel_p1_uranus_bigtts', name: 'Rachel', lang: 'en-US', gender: 'female' },
  {
    id: 'en_female_pleasant-female_uranus_bigtts',
    name: 'Elaine',
    lang: 'en-US',
    gender: 'female',
  },
  { id: 'en_female_natasha_uranus_bigtts', name: 'Natasha', lang: 'en-US', gender: 'female' },
  { id: 'en_female_nadia_uranus_bigtts', name: 'Blair', lang: 'en-US', gender: 'female' },
  { id: 'en_female_myra_cmb_uranus_bigtts', name: 'Sunny', lang: 'en-US', gender: 'female' },
  { id: 'en_female_myra_uranus_bigtts', name: 'Myra', lang: 'en-US', gender: 'female' },
  { id: 'en_male_motivational-coach_uranus_bigtts', name: 'Rory', lang: 'en-US', gender: 'male' },
  { id: 'en_male_michael-mouse_uranus_bigtts', name: 'Chip', lang: 'en-US', gender: 'male' },
  { id: 'en_male_michael_uranus_bigtts', name: 'Hank', lang: 'en-US', gender: 'male' },
  { id: 'en_female_mel_uranus_bigtts', name: 'Mel', lang: 'en-US', gender: 'female' },
  {
    id: 'en_female_lana_del_rey_parky_s_p1_uranus_bigtts',
    name: 'Ivy',
    lang: 'en-US',
    gender: 'female',
  },
  {
    id: 'en_female_lana_del_rey_kelley_d_p1_uranus_bigtts',
    name: 'Lynn',
    lang: 'en-US',
    gender: 'female',
  },
  { id: 'en_male_kevin_uranus_bigtts', name: 'Kevin', lang: 'en-US', gender: 'male' },
  { id: 'en_male_josh_uranus_bigtts', name: 'Josh', lang: 'en-US', gender: 'male' },
  { id: 'en_male_joker_uranus_bigtts', name: 'Joker', lang: 'en-US', gender: 'male' },
  { id: 'en_female_joanne_uranus_bigtts', name: 'Joanne', lang: 'en-US', gender: 'female' },
  { id: 'en_male_jimmy_uranus_bigtts', name: 'Jimmy', lang: 'en-US', gender: 'male' },
  { id: 'en_male_jidongchuanjiaoshi_uranus_bigtts', name: 'Blaze', lang: 'en-US', gender: 'male' },
  { id: 'en_female_jenny_uranus_bigtts', name: 'Jenny', lang: 'en-US', gender: 'female' },
  { id: 'en_male_jamie_uranus_bigtts', name: 'Jamie', lang: 'en-US', gender: 'male' },
  { id: 'en_female_hayley_uranus_bigtts', name: 'Hayley', lang: 'en-US', gender: 'female' },
  { id: 'en_male_gollum_uranus_bigtts', name: 'Gollum', lang: 'en-US', gender: 'male' },
  { id: 'en_male_godfather_uranus_bigtts', name: 'Godfather', lang: 'en-US', gender: 'male' },
  { id: 'en_male_fernando-martinez_uranus_bigtts', name: 'Felix', lang: 'en-US', gender: 'male' },
  {
    id: 'en_female_female_tutor_ms-jenny_uranus_bigtts',
    name: 'Holly',
    lang: 'en-US',
    gender: 'female',
  },
  { id: 'en_male_excited-male-voice_uranus_bigtts', name: 'Jasper', lang: 'en-US', gender: 'male' },
  { id: 'en_male_evil-guy-oxley_uranus_bigtts', name: 'Harrison', lang: 'en-US', gender: 'male' },
  { id: 'en_male_diyuwenrounan_uranus_bigtts', name: 'Julian', lang: 'en-US', gender: 'male' },
  { id: 'en_male_david_uranus_bigtts', name: 'David', lang: 'en-US', gender: 'male' },
  { id: 'en_male_cowboy_john_b_uranus_bigtts', name: 'John', lang: 'en-US', gender: 'male' },
  { id: 'en_male_cowboy-bob_uranus_bigtts', name: 'Bob', lang: 'en-US', gender: 'male' },
  { id: 'en_male_chandler_p1_uranus_bigtts', name: 'Leo', lang: 'en-US', gender: 'male' },
  { id: 'en_male_bruce_uranus_bigtts', name: 'Adrian', lang: 'en-US', gender: 'male' },
  { id: 'en_female_brittney_pimintel_uranus_bigtts', name: 'Zoe', lang: 'en-US', gender: 'female' },
  { id: 'en_female_brittney_uranus_bigtts', name: 'Brittney', lang: 'en-US', gender: 'female' },
  { id: 'en_male_brad_pitt_p1_uranus_bigtts', name: 'Brad_Pitt', lang: 'en-US', gender: 'male' },
  { id: 'en_male_bill_jones_corey_uranus_bigtts', name: 'Bill', lang: 'en-US', gender: 'male' },
  {
    id: 'en_female_authoritative-informative_uranus_bigtts',
    name: 'Margaret',
    lang: 'en-US',
    gender: 'female',
  },
  { id: 'en_female_allison_uranus_bigtts', name: 'Allison', lang: 'en-US', gender: 'female' },
  { id: 'en_male_alex_uranus_bigtts', name: 'Alex', lang: 'en-US', gender: 'male' },
  { id: 'en_male_adam-imitation_uranus_bigtts', name: 'Rowan', lang: 'en-US', gender: 'male' },
  { id: 'de_male_sven_uranus_bigtts', name: 'Sven', lang: 'de-DE', gender: 'male' },
  { id: 'de_female_bv081_uranus_bigtts', name: 'Stella', lang: 'de-DE', gender: 'female' },
  { id: 'ar_female_fatma_uranus_bigtts', name: 'Fatma', lang: 'ar', gender: 'female' },
  {
    id: 'ICL_uranus_zh_female_qingyingduoduo_tob',
    name: '轻盈朵朵 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_male_shuanglangshaonian_tob',
    name: '爽朗少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_female_reqingaina_tob',
    name: '热情艾娜 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_wenwanshanshan_tob',
    name: '温婉珊珊 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'ICL_uranus_zh_male_qingxinmumu_tob', name: '清新沐沐 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_tiancaitongzhuo_tob',
    name: '天才同桌 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_zixinqingnian_tob',
    name: '自信青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_zifuqingnian_tob',
    name: '自负青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_zhongerqingnian_tob',
    name: '中二青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_zhishuaiqingnian_tob',
    name: '直率青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_zhangjianxiake_tob',
    name: '仗剑侠客 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_zhangjianjunzi_tob',
    name: '仗剑君子 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_yuanqishaonian_tob',
    name: '元气少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_younidashu_tob', name: '油腻大叔 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_yiqishaonian_tob',
    name: '意气少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_wennuanshaonian_tob',
    name: '温暖少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_xuebatongzhuo_tob',
    name: '学霸同桌 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_xiaohouye_tob', name: '小侯爷 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_wenshunshaonian_tob',
    name: '温顺少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_wenrunxuezhe_tob',
    name: '温润学者 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_wenrouxuezhang_tob',
    name: '温柔学长 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_wenrounanyou_tob',
    name: '温柔男友 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_tianxinanyou_tob',
    name: '甜系男友 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_siwenqingnian_tob',
    name: '斯文青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_shenchenzongcai_tob',
    name: '深沉总裁 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_satuoqingnian_tob',
    name: '洒脱青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_sajiaonanyou_tob',
    name: '撒娇男友 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_sajiaonansheng_tob',
    name: '撒娇男生 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_ruyazongcai_tob', name: '儒雅总裁 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'ICL_uranus_zh_male_ruyajunzi_tob', name: '儒雅君子 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_rexueshaonian_tob',
    name: '热血少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_qinqieqingnian_tob',
    name: '亲切青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_qingshuangshaonian_tob',
    name: '清爽少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_qingseqingnian_tob',
    name: '青涩青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_pianpiangongzi_tob',
    name: '翩翩公子 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_neiliancaijun_tob',
    name: '内敛才俊 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_nianrennanyou_tob',
    name: '粘人男友 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_xiaozhangxiaoge_tob',
    name: '嚣张小哥 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_mengdongqingnian_tob',
    name: '懵懂青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_lingyunqingnian_tob',
    name: '凌云青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_lengmoxiongzhang_tob',
    name: '冷漠兄长 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_lengmonanyou_tob',
    name: '冷漠男友 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_lenglianxueba_tob',
    name: '冷脸学霸 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_lenglianxiongzhang_tob',
    name: '冷脸兄长 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_lengjungaozhi_tob',
    name: '冷峻高智 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_lengaozongcai_tob',
    name: '冷傲总裁 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_kailangqingnian_tob',
    name: '开朗青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_junyigongzi_tob', name: '俊逸公子 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_jingyingqingnian_tob',
    name: '精英青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_jijiazhineng_tob',
    name: '机甲智能 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_huzishushu_tob', name: '胡子叔叔 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'ICL_uranus_zh_male_huoponanyou_tob', name: '活泼男友 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_huoliqingnian_tob',
    name: '活力青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_gugaogongzi_tob', name: '孤高公子 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_gaolengzongcai_tob',
    name: '高冷总裁 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_ganjingshaonian_tob',
    name: '干净少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_ruyagongzi_tob', name: '儒雅公子 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_fengfashaonian_tob',
    name: '风发少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_diyinchenyu_tob', name: '低音沉郁 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_cujingnansheng_tob',
    name: '醋精男生 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_cixingnansang_tob',
    name: '磁性男嗓 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_chengshuzongcai_tob',
    name: '成熟总裁 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_chanruoshaoye_tob',
    name: '孱弱少爷 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_paoxiaoxiaoge_tob',
    name: '咆哮小哥 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_chunhoudiyin_tob',
    name: '醇厚低音 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_bujiqingnian_tob',
    name: '不羁青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_bingruoshaonian_tob',
    name: '病弱少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_bingjiaoshaonian_tob',
    name: '病娇少年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_bingjiaonanyou_tob',
    name: '病娇男友 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_badaoshaoye_tob', name: '霸道少爷 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_aomanqingnian_tob',
    name: '傲慢青年 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_aojiaojingying_tob',
    name: '傲娇精英 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_aojiaogongzi_tob',
    name: '傲娇公子 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_female_xiemeiyujie_tob',
    name: '邪魅御姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_tianmeixiaoyu_tob',
    name: '甜美小雨 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_tianmeixiaoju_tob',
    name: '甜美小橘 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_qingxinshaonv_tob',
    name: '倾心少女 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_xingganmeihuo_tob',
    name: '性感魅惑 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_linjuayi_tob',
    name: '邻居阿姨  2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_huoponvhai_tob',
    name: '活泼女孩  2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_heainainai_tob',
    name: '和蔼奶奶  2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_wumeikeren_tob',
    name: '妩媚可人 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_bingruoshaonv_tob',
    name: '病弱少女  2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_xiemeinvwang_tob',
    name: '邪魅女王 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'ICL_uranus_en_male_zayne_tob', name: 'Zayne 2.0', lang: 'en-US', gender: 'male' },
  { id: 'ICL_uranus_en_male_xavier_tob', name: 'Xavier 2.0', lang: 'en-US', gender: 'male' },
  {
    id: 'ICL_uranus_en_male_cartoon_chef_tob',
    name: 'Cartoon Chef 2.0',
    lang: 'en-US',
    gender: 'male',
  },
  { id: 'ICL_uranus_en_male_clown_man_tob', name: 'Clown Man 2.0', lang: 'en-US', gender: 'male' },
  { id: 'ICL_uranus_en_male_jigsaw_tob', name: 'Jigsaw 2.0', lang: 'en-US', gender: 'male' },
  { id: 'ICL_uranus_en_male_noah_tob', name: 'Noah 2.0', lang: 'en-US', gender: 'male' },
  { id: 'ICL_uranus_en_male_chucky_tob', name: 'Chucky 2.0', lang: 'en-US', gender: 'male' },
  { id: 'ICL_uranus_en_male_alastor_tob', name: 'Alastor 2.0', lang: 'en-GB', gender: 'male' },
  { id: 'ICL_uranus_en_male_ethan_tob', name: 'Ethan 2.0', lang: 'en-AU', gender: 'male' },
  { id: 'ICL_uranus_en_female_charlie_tob', name: 'Charlie 2.0', lang: 'en-US', gender: 'female' },
  { id: 'zh_female_xiaoxue_uranus_bigtts', name: '儿童绘本 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'zh_female_tianmeixiaoyuan_uranus_bigtts',
    name: '甜美小源 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_male_yourougongzi_tob',
    name: '优柔公子 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_youmoshushu_tob', name: '幽默叔叔 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'ICL_uranus_zh_male_youmodaye_tob', name: '幽默大爷 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_xuebanantongzhuo_tob',
    name: '学霸男同桌 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_wenrouneilian_tob',
    name: '温柔内敛 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_naiqixiaosheng_tob',
    name: '奶气小生 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_guayanxiaoge_tob',
    name: '寡言小哥 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_wenrounantongzhuo_tob',
    name: '温柔男同桌 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_tiexinnanyou_tob',
    name: '贴心男友 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_dichenqianquan_tob',
    name: '低沉缱绻 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_shenmifashi_tob', name: '神秘法师 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_shaonianjiangjun_tob',
    name: '少年将军 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_qinglangwenrun_tob',
    name: '清朗温润 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_chenwenyouya_tob',
    name: '沉稳优雅 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_menyoupingxiaoge_tob',
    name: '闷油瓶小哥 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_qinglengjingui_tob',
    name: '清冷矜贵 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_lengkugege_tob', name: '冷酷哥哥 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_lengjunshangsi_tob',
    name: '冷峻上司 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_lanyincaohunshi_tob',
    name: '蓝银草魂师 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_guaogongzi_tob', name: '孤傲公子 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_chunzhenxuedi_tob',
    name: '纯真学弟 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_qingyisugan_tob', name: '清逸苏感 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_bingruogongzi_tob',
    name: '病弱公子 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_bingjiaogege_tob',
    name: '病娇哥哥 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_bingjiaodidi_tob',
    name: '病娇弟弟 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_aomanshaoye_tob', name: '傲慢少爷 2.0', lang: 'zh-CN', gender: 'male' },
  { id: 'ICL_uranus_zh_male_anrenqinzhu_tob', name: '黯刃秦主 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_female_xingganyujie_tob',
    name: '性感御姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_wumeiyujie_tob',
    name: '妩媚御姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_tiexinnvyou_tob',
    name: '贴心女友 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_qinglenggaoya_tob',
    name: '清冷高雅 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_tianmeijiaoqiao_tob',
    name: '甜美娇俏 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_jinglingxiangdao_tob',
    name: '精灵向导 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'ICL_uranus_zh_female_jiaxiaozi_tob', name: '假小子 2.0', lang: 'zh-CN', gender: 'female' },
  {
    id: 'ICL_uranus_zh_female_jiaoruoluoli_tob',
    name: '娇弱萝莉 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_chunzhenshaonv_tob',
    name: '纯真少女 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_chengshujiejie_tob',
    name: '成熟姐姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_bingjiaojiejie_tob',
    name: '病娇姐姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_aojiaonvyou_tob',
    name: '傲娇女友 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'ICL_uranus_zh_male_yangyang_tob', name: '炀炀 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_yangguangyangyang_tob',
    name: '阳光洋洋 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_shuanglangxiaoyang_tob',
    name: '爽朗小阳 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_jilingxiaohuo_tob',
    name: '机灵小伙 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_qinqiexiaozhuo_tob',
    name: '亲切小卓 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  { id: 'ICL_uranus_zh_male_qingxinbobo_tob', name: '清新波波 2.0', lang: 'zh-CN', gender: 'male' },
  {
    id: 'ICL_uranus_zh_male_cujingnanyou_tob',
    name: '醋精男友 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_chenwenmingzai_tob',
    name: '沉稳明仔 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_male_badaozongcai_tob',
    name: '霸道总裁 2.0',
    lang: 'zh-CN',
    gender: 'male',
  },
  {
    id: 'ICL_uranus_zh_female_chuliannvyou_tob',
    name: '初恋女友 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_wenroubaiyueguang_tob',
    name: '温柔白月光 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_tiexinmeimei_tob',
    name: '贴心妹妹 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_tiexinguimi_tob',
    name: '贴心闺蜜 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_xiuliqianqian_tob',
    name: '秀丽倩倩 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_yuanqitianmei_tob',
    name: '元气甜妹 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_zhixinjiejie_tob',
    name: '知心姐姐 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_ruanmengtuanzi_tob',
    name: '软萌团子 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_ruanmengtangtang_tob',
    name: '软萌糖糖 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_qingxixiaoxue_tob',
    name: '清晰小雪 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_qingtiantaotao_tob',
    name: '清甜桃桃 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_qingtianmeimei_tob',
    name: '清甜莓莓 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_nuanxinqianqian_tob',
    name: '暖心茜茜 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_lixingyuanzi_tob',
    name: '理性圆子 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_lingdongxinxin_tob',
    name: '灵动欣欣 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_kaixinxiaohong_tob',
    name: '开心小鸿 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_kailangtingting_tob',
    name: '开朗婷婷 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_guaiqiaokeer_tob',
    name: '乖巧可儿 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  {
    id: 'ICL_uranus_zh_female_chunchenvsheng_tob',
    name: '纯澈女生 2.0',
    lang: 'zh-CN',
    gender: 'female',
  },
  { id: 'en_female_stokie_uranus_bigtts', name: 'Stokie', lang: 'en-US', gender: 'female' },
  { id: 'en_female_dacey_uranus_bigtts', name: 'Dacey', lang: 'en-US', gender: 'female' },
  { id: 'en_male_tim_uranus_bigtts', name: 'Tim', lang: 'en-US', gender: 'male' },
  { id: 'en_male_bill-jones_uranus_bigtts', name: 'Jones', lang: 'en-US', gender: 'male' },
];
