//! The Chinese pipeline end to end, against the JavaScript frontend.
//!
//! Phase 5 pinned the *readings* — one Han run at a time, one space per syllable
//! (`tests/zh_parity.rs`). This pins what phase 6 added around them: the numeral
//! reading, the punctuation map, the script split, and jieba's word boundaries,
//! which is where the spaces in the output come from.
//!
//! Three independent pins, because they fail for different reasons:
//!
//! - **The corpus** (`tests/fixtures/zh-frontend-parity.json`) is 46 whole
//!   sentences and the string the JavaScript produces for each, generated by
//!   `tests/unit/models/phonemize/zh-frontend-parity.test.ts`. Both sides are
//!   pinned to it, so neither can drift alone. This is the broad check.
//! - **The strings in `matches_the_javascript_suite_sample_for_sample`** are the
//!   JavaScript suite's *own* assertions (`tests/unit/models/phonemize.test.ts`),
//!   written by hand from a verified run. They are redundant with the corpus and
//!   worth it: they are readable, they name the behaviour they cover, and they
//!   were written before the corpus existed.
//! - **The structural tests** cover the one step where the two pipelines
//!   deliberately differ — a Latin run goes to the English engine here and to
//!   espeak there — and the refusals, which a corpus of successes cannot record.
//!
//! # What "parity" does and does not mean here
//!
//! Exact string equality for Han text, numerals and punctuation. **Not** for
//! Latin text: `chinese.ts` hands a Latin run to espeak, this pipeline hands it to
//! its CMU Dict backend (the phase 4 decision), so the two agree on an initialism
//! and can differ on a word espeak would have invented a pronunciation for. The
//! corpus therefore contains no Latin text at all — the generator's Latin
//! phonemizer throws rather than letting one in — and mixed text is tested for the
//! property that actually has to hold: the Han either side of a Latin run comes
//! out unchanged.

mod common;

use common::{chinese_options, chinese_phonemizer};
use phonemize::{PhonemizeError, PhonemizeResult, Phonemizer};
use serde::Deserialize;

/// The corpus the JavaScript generated.
#[derive(Debug, Deserialize)]
struct Corpus {
    samples: Vec<Sample>,
}

#[derive(Debug, Deserialize)]
struct Sample {
    input: String,
    /// What `ChinesePhonemizer.phonemize` produces for it.
    js: String,
}

fn corpus() -> Corpus {
    serde_json::from_str(include_str!("fixtures/zh-frontend-parity.json"))
        .expect("the corpus parses")
}

/// Phonemize with the Chinese frontend, or say why not.
fn phonemize(phonemizer: &Phonemizer, text: &str) -> PhonemizeResult {
    phonemizer
        .phonemize_with(text, &chinese_options())
        .unwrap_or_else(|error| panic!("{text:?}: {error}"))
}

#[test]
fn matches_the_javascript_pipeline_on_the_corpus() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    let mut failures = Vec::new();
    let samples = corpus().samples;
    for sample in &samples {
        let rust = phonemize(&phonemizer, &sample.input).phonemes;
        if rust != sample.js {
            failures.push(format!(
                "{}\n  javascript {:?}\n  rust       {:?}",
                serde_json::to_string(&sample.input).unwrap(),
                sample.js,
                rust
            ));
        }
    }

    // Every sample, not the first failure: a wrong reading usually means the
    // segmentation went wrong somewhere earlier, and one example of that is much
    // less useful than the shape of all of them.
    assert!(
        failures.is_empty(),
        "{} of {} samples differ:\n{}",
        failures.len(),
        samples.len(),
        failures.join("\n")
    );
}

/// The JavaScript suite's own expectations, verbatim.
///
/// Each of these is an assertion in `tests/unit/models/phonemize.test.ts`, so a
/// failure here means one of two things and both are worth knowing: the Rust
/// pipeline diverged from JavaScript, or JavaScript changed and its own suite is
/// the thing that is now out of date.
#[test]
fn matches_the_javascript_suite_sample_for_sample() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // The P5 spec's §3.11.7 example: a numeral, a decimal, a percentage, a
    // full-width full stop, and the tone sandhi pinyin-pro applies to 增长.
    assert_eq!(
        phonemize(&phonemizer, "第 3 季度营收增长了 15.6%。").phonemes,
        "ti↘ sa→n ʨi↘tu↘ i↗ŋʂou→ ʦə→ŋꭧa↓ŋ lɤ pai↓fə→nꭧɻ̩→ʂɻ̩↗u↓ tjɛ↓nljou↘."
    );

    // The space comes *after* the mark, because `mapPunctuation` emits `", "`
    // and the runs are concatenated with nothing inserted between them. Putting
    // one in front of every mark as well is the deviation the P5 spec calls B.
    assert_eq!(
        phonemize(&phonemizer, "你好世界。").phonemes,
        "ni↓xau↓ ʂɻ̩↘ʨje↘."
    );

    assert_eq!(
        phonemize(&phonemizer, "你好   世界").phonemes,
        "ni↓xau↓ ʂɻ̩↘ʨje↘"
    );
    assert_eq!(
        phonemize(&phonemizer, "妈麻马骂。").phonemes,
        "ma→ma↗ma↓ ma↘."
    );

    // `-` is not in Kokoro's vocabulary, and `%` is already spoken by the
    // numeral conversion. Emitting either would be pointless at best.
    assert_eq!(phonemize(&phonemizer, "好-坏").phonemes, "xau↓xwai↘");

    // Nothing to say is not an error.
    assert_eq!(phonemize(&phonemizer, "   ").phonemes, "");
}

#[test]
fn puts_one_space_between_words_and_none_inside_them() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // The user's report, and the reason jieba is in the pipeline at all: 人设
    // and 曾经 are each one word, and the model paused between their characters
    // when every syllable was separated. One word means one unit means no
    // boundary — so this is two spaces in the whole string, not five.
    let phonemes = phonemize(&phonemizer, "人设曾经").phonemes;
    assert_eq!(phonemes, "ɻə↗nʂɤ↘ ʦʰə↗ŋʨi→ŋ");
    assert_eq!(phonemes.matches(' ').count(), 1);

    // And the boundaries are jieba's, not a syllable count: 中华人民共和国 is
    // one word here, so the space after it is the only one in the first half.
    assert_eq!(
        phonemize(&phonemizer, "中华人民共和国武汉市长江大桥").phonemes,
        "ꭧʊ→ŋxwa↗ɻə↗nmi↗nkʊ↘ŋxɤ↗kwo↗ u↓xa↘nʂɻ̩↘ ꭧa↓ŋʨja→ŋta↘ʨʰjau↗"
    );
}

#[test]
fn a_latin_run_leaves_the_han_around_it_alone() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // The contract, and the property that survives the two sides using different
    // English engines: the runs are concatenated with nothing inserted, so the
    // whole is exactly its parts in order. Asserted by building the expected
    // string out of three separate calls rather than by writing it down, so the
    // test says "the Han is unaffected" rather than pinning whatever the English
    // engine happened to produce this month.
    let mixed = phonemize(&phonemizer, "你好ABC世界").phonemes;
    let expected = format!(
        "{}{}{}",
        phonemize(&phonemizer, "你好").phonemes,
        phonemize(&phonemizer, "ABC").phonemes,
        phonemize(&phonemizer, "世界").phonemes
    );
    assert_eq!(mixed, expected);

    // The Latin part really is the English engine's, and not the letters passed
    // through: an initialism is spelled out, and the schwa for `A` is CMU Dict's
    // entry for the letter — which is what `en_g2p.rs` pins as phase 4's answer,
    // and what espeak would have answered differently.
    assert_eq!(phonemize(&phonemizer, "ABC").phonemes, "ə bˈiː sˈiː");

    // A mixed-case word is read as a word, not spelled.
    assert!(phonemize(&phonemizer, "Hello世界")
        .phonemes
        .starts_with("həlˈoʊ"));
}

#[test]
fn a_numerals_reading_is_not_a_separate_run() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // The numeral has to become Han *before* the runs are split, or it would land
    // in an `other` run and be dropped as punctuation — unheard, and silently.
    // 只 is what makes this visible: as 三只 it is read with the numeral in one
    // word, and a split run would leave 三 missing and the word boundary wrong.
    assert_eq!(
        phonemize(&phonemizer, "我有3只猫").phonemes,
        "wo↓ jou↓ sa→nꭧɻ̩→ mau→"
    );

    // And the reading itself, so a failure says which half broke.
    assert_eq!(phonemize(&phonemizer, "123").phonemes, "i↘pai↓ɚ↘ʂɻ̩↗ sa→n");
    assert_eq!(
        phonemize(&phonemizer, "123.45").phonemes,
        "i↘pai↓ɚ↘ʂɻ̩↗ sa→ntjɛ↓n sɹ̩↘u↓"
    );
}

#[test]
fn a_run_this_frontend_cannot_read_is_dropped_rather_than_read_wrong() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // Kana is `other` to `chinese.ts` — it has no kana alternative in its run
    // pattern — and `keepPunctuation` has no kana in its set, so it is dropped.
    // Reading it with the Chinese syllable table would be worse than dropping it,
    // which is why the Chinese pipeline has no kana run at all.
    //
    // **Dropping it also costs the word boundary**, and that is not a bug in
    // either implementation: 你好 and 世界 are two Han runs with an unreadable run
    // between them, and jieba segments each run on its own — so the space that
    // `你好世界` gets from being one two-word run does not appear. Asserted as the
    // concatenation rather than as the fixed string so the test says which
    // property is being checked, and pinned against the JavaScript by the corpus.
    assert_eq!(
        phonemize(&phonemizer, "你好あ世界").phonemes,
        format!(
            "{}{}",
            phonemize(&phonemizer, "你好").phonemes,
            phonemize(&phonemizer, "世界").phonemes
        )
    );
}

#[test]
fn refuses_a_character_pinyin_pro_cannot_read() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // U+3400 is in the Han range and absent from the dictionary. Returning the
    // rest of the sentence — as the verification script did — drops the character
    // from the audio without a trace, and a sentence missing a word sounds like a
    // sentence.
    let error = phonemizer
        .phonemize_with("你好㐀", &chinese_options())
        .expect_err("㐀 has no reading");

    assert_eq!(error.code(), "unreadable-characters");
    assert!(matches!(error, PhonemizeError::Pipeline(_)));
}

#[test]
fn refuses_to_phonemize_before_the_dictionary_arrived() {
    // A fresh instance has no segmenter, and a sentence read without word
    // boundaries is audible (人设, 曾经) — so this is a failure rather than a
    // sentence that comes out with the wrong spacing.
    let phonemizer = Phonemizer::new();

    let error = phonemizer
        .phonemize_with("你好世界", &chinese_options())
        .expect_err("nothing was prepared");

    assert_eq!(error.code(), "dictionary-not-loaded");
    assert!(matches!(error, PhonemizeError::NotPrepared { .. }));
}

#[test]
fn every_corpus_sample_passes_the_vocabulary_gate() {
    // Implicit in `phonemize_with`, which validates before returning — but
    // asserted separately because the gate is the thing that turns "a character
    // the tokenizer would silently delete" into a failure, and a corpus is the
    // cheapest way to check it across a lot of input at once. If this ever fails
    // it will fail inside `phonemize` above first; the point of having it twice is
    // that the reason is in the message.
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    for sample in corpus().samples {
        let result = phonemizer.phonemize_with(&sample.input, &chinese_options());
        assert!(
            result.is_ok(),
            "{:?} failed the gate: {}",
            sample.input,
            result.expect_err("checked")
        );
    }
}
