//! The Chinese pipeline end to end, against the corpus the JavaScript frontend
//! left behind.
//!
//! Phase 5 pinned the *readings* — one Han run at a time, one space per syllable
//! (`tests/zh_parity.rs`). This pins what phase 6 added around them: the numeral
//! reading, the punctuation map, the script split, and jieba's word boundaries,
//! which is where the spaces in the output come from.
//!
//! # Two pipelines, and which test runs which
//!
//! Phase 9D put Mandarin tone sandhi and the erhua coda in front of the syllable
//! table (`tests/tone_sandhi.rs`), and the JavaScript frontend had neither — so
//! the shipped pipeline and the corpus no longer describe the same thing.
//! `pipeline::ToneRules` is the seam: `Off` is the phase 6 pipeline exactly, and
//! `On` is what ships (`lib.rs` passes `On`).
//!
//! The corpus stays a *parity* corpus, and the tests below keep it one by asking
//! for `Off`, through [`legacy_phonemes`]. **The shipped pipeline is checked
//! against it too**, in `the_tone_rules_change_exactly_these_samples`: that test
//! holds the list of samples the tone rules move, with the value each moves to,
//! and asserts from both ends — a sample in the list must differ and match its
//! new value, and one that is not in the list must be identical under both
//! pipelines. So "the tone rules are the only difference" is asserted rather
//! than hoped for, and any later change that moves the output for some other reason
//! fails here instead of quietly rewriting the corpus.
//!
//! Three independent pins, because they fail for different reasons:
//!
//! - **The corpus** (`tests/fixtures/zh-frontend-parity.json`) is 47 whole
//!   sentences and the string the JavaScript produced for each, generated by
//!   `tests/unit/models/phonemize/zh-frontend-parity.test.ts` before phase 8
//!   deleted that chain. It is frozen — the generator is gone — so this test is
//!   what keeps the Rust output pinned to it. This is the broad check.
//! - **The strings in `matches_the_javascript_suite_sample_for_sample`** were the
//!   JavaScript suite's *own* assertions (`tests/unit/models/phonemize.test.ts`),
//!   written by hand from a verified run. They are redundant with the corpus and
//!   worth it: they are readable, they name the behaviour they cover, and they
//!   were written before the corpus existed.
//! - **The structural tests** cover the one step where the two pipelines
//!   deliberately differ — a Latin run goes to the English engine here and to
//!   espeak there — and the refusals, which a corpus of successes cannot record.
//!
//! # What "parity" does and does not mean here
//!
//! Exact string equality for Han text, numerals and punctuation. **Not** for
//! Latin text: `chinese.ts` hands a Latin run to espeak, this pipeline hands it to
//! its CMU Dict backend (the phase 4 decision), so the two agree on an initialism
//! and can differ on a word espeak would have invented a pronunciation for. The
//! corpus therefore contains no Latin text at all — the generator's Latin
//! phonemizer throws rather than letting one in — and mixed text is tested for the
//! property that actually has to hold: the Han either side of a Latin run comes
//! out unchanged.

mod common;

use common::{chinese_options, chinese_phonemizer};
use phonemize::g2p::zh::SegmenterZh;
use phonemize::pipeline::{self, ToneRules};
use phonemize::tn::wetext::Normalizer;
use phonemize::{PhonemizeError, PhonemizeResult, Phonemizer};
use serde::Deserialize;

/// The corpus the JavaScript generated.
#[derive(Debug, Deserialize)]
struct Corpus {
    samples: Vec<Sample>,
}

#[derive(Debug, Deserialize)]
struct Sample {
    input: String,
    /// What `ChinesePhonemizer.phonemize` produces for it.
    js: String,
}

fn corpus() -> Corpus {
    serde_json::from_str(include_str!("fixtures/zh-frontend-parity.json"))
        .expect("the corpus parses")
}

/// Phonemize with the Chinese frontend, or say why not.
fn phonemize(phonemizer: &Phonemizer, text: &str) -> PhonemizeResult {
    phonemizer
        .phonemize_with(text, &chinese_options())
        .unwrap_or_else(|error| panic!("{text:?}: {error}"))
}

/// The phase 6 pipeline, for a test that compares against the JavaScript.
///
/// The corpus is the JavaScript frontend's output, and the JavaScript frontend
/// did no tone sandhi, no erhua and no WeText: it read numerals with
/// `numbersToHan` and nothing else. So a test that compares against it has to ask
/// for [`ToneRules::Off`] *and* no text normalizer. It cannot go through
/// `Phonemizer` — that ships `On`, and since phase 9E it ships the shipped
/// numerals too, and it takes no option for either, deliberately: whether the
/// v1.0 voices should sandhi, and whether they should read a date as a date, are
/// decisions for the caller and not for a sentence (see `pipeline::ToneRules`).
/// So this drives the pipeline directly with its own segmenter, built once per
/// test rather than once per sentence.
///
/// **[`Self::phonemes`] takes both switches**, and that is what makes the two
/// tables that follow readable as a decomposition rather than a pile of pins:
/// phase 6 is `(Off, None)`, the tone rules alone are `(On, None)`, the numeral
/// step alone is `(Off, Some)` if anyone needs it, and the shipped pipeline is
/// `(On, Some)`.
struct Legacy {
    segmenter: SegmenterZh,
}

/// `None` only when the caller asked to skip the dictionary tests by name; the
/// rule for that is in [`common`].
fn legacy() -> Option<Legacy> {
    let compressed = common::jieba_dictionary_bytes()?;

    // The registry decompresses inside the wasm; a test that wants the word list
    // has to unpack the frame itself.
    let mut decoder =
        ruzstd::decoding::StreamingDecoder::new(&compressed[..]).expect("a zstd frame");
    let mut dictionary = Vec::new();
    std::io::Read::read_to_end(&mut decoder, &mut dictionary).expect("the frame decompresses");

    Some(Legacy {
        segmenter: SegmenterZh::from_dictionary(&dictionary).expect("the dictionary loads"),
    })
}

impl Legacy {
    fn phonemes(&self, text: &str, tone_rules: ToneRules, tn: Option<&Normalizer>) -> String {
        // `None` for the English backend: the corpus has no Latin text in it,
        // because the two pipelines deliberately use different English engines
        // for a Latin run (see the module comment above).
        pipeline::phonemize_zh(text, &self.segmenter, None, tone_rules, tn)
            .unwrap_or_else(|error| panic!("{text:?}: {error}"))
            .phonemes
    }

    /// The phase 6 pipeline, exactly: no tone rules and no WeText.
    fn phase6(&self, text: &str) -> String {
        self.phonemes(text, ToneRules::Off, None)
    }
}

#[test]
fn matches_the_javascript_pipeline_on_the_corpus() {
    let Some(legacy) = legacy() else {
        return;
    };

    let mut failures = Vec::new();
    let samples = corpus().samples;
    for sample in &samples {
        let rust = legacy.phase6(&sample.input);
        if rust != sample.js {
            failures.push(format!(
                "{}\n  javascript {:?}\n  rust       {:?}",
                serde_json::to_string(&sample.input).unwrap(),
                sample.js,
                rust
            ));
        }
    }

    // Every sample, not the first failure: a wrong reading usually means the
    // segmentation went wrong somewhere earlier, and one example of that is much
    // less useful than the shape of all of them.
    assert!(
        failures.is_empty(),
        "{} of {} samples differ:\n{}",
        failures.len(),
        samples.len(),
        failures.join("\n")
    );
}

/// The JavaScript suite's own expectations, verbatim.
///
/// Each of these is an assertion in `tests/unit/models/phonemize.test.ts`, so a
/// failure here means one of two things and both are worth knowing: the Rust
/// pipeline diverged from JavaScript, or JavaScript changed and its own suite is
/// the thing that is now out of date.
#[test]
fn matches_the_javascript_suite_sample_for_sample() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };
    let Some(legacy) = legacy() else {
        return;
    };

    // The P5 spec's §3.11.7 example: a numeral, a decimal, a percentage, a
    // full-width full stop, and the tone sandhi pinyin-pro applies to 增长. It
    // goes through `legacy` for the same reason the corpus does — these are the
    // JavaScript suite's own expectations, and the tone rules move one of them
    // (你好世界。 gains a second tone on 你).
    assert_eq!(
        legacy.phase6("第 3 季度营收增长了 15.6%。"),
        "ti↘ sa→n ʨi↘tu↘ i↗ŋʂou→ ʦə→ŋꭧa↓ŋ lɤ pai↓fə→nꭧɻ̩→ʂɻ̩↗u↓ tjɛ↓nljou↘."
    );

    // The space comes *after* the mark, because `mapPunctuation` emits `", "`
    // and the runs are concatenated with nothing inserted between them. Putting
    // one in front of every mark as well is the deviation the P5 spec calls B.
    assert_eq!(legacy.phase6("你好世界。"), "ni↓xau↓ ʂɻ̩↘ʨje↘.");

    assert_eq!(legacy.phase6("你好   世界"), "ni↓xau↓ ʂɻ̩↘ʨje↘");
    assert_eq!(legacy.phase6("妈麻马骂。"), "ma→ma↗ma↓ ma↘.");

    // `-` is not in Kokoro's vocabulary, and `%` is already spoken by the
    // numeral conversion. Emitting either would be pointless at best.
    assert_eq!(legacy.phase6("好-坏"), "xau↓xwai↘");

    // Nothing to say is not an error.
    assert_eq!(legacy.phase6("   "), "");

    // And the shipped pipeline on the same sentences, so that both pipelines are
    // pinned for one input rather than one being pinned and the other assumed.
    // 你好 is the one that moved: *ní hǎo*.
    assert_eq!(
        phonemize(&phonemizer, "你好世界。").phonemes,
        "ni↗xau↓ ʂɻ̩↘ʨje↘."
    );
    assert_eq!(
        phonemize(&phonemizer, "妈麻马骂。").phonemes,
        "ma→ma↗ma↓ ma↘."
    );
    assert_eq!(phonemize(&phonemizer, "好-坏").phonemes, "xau↓xwai↘");
    assert_eq!(phonemize(&phonemizer, "   ").phonemes, "");
}

/// The two inputs the phase 6 task names as its acceptance examples, verbatim,
/// through the shipped pipeline — so these are the strings the tone rules produce
/// and not the ones the JavaScript did.
///
/// The first is also a corpus sample, so JavaScript pins it independently — the
/// duplication is the point, and the same shape as the suite's own assertions
/// above. It is a numeral at the *end* of a sentence, which none of the other
/// numeral samples covers, and the failure it guards is the interesting one: a
/// trailing numeral that never becomes Han would be dropped as punctuation and
/// the sentence would simply stop early. 你好 is *ní hǎo*, which is why the first
/// syllable carries `↗` and not `↓`.
///
/// The second cannot be a corpus sample, because it has a Latin run and the two
/// pipelines deliberately use different English engines there (see the module
/// comment). What has to hold is checked instead: the Han either side is
/// unchanged and the runs are concatenated with nothing inserted.
#[test]
fn handles_the_acceptance_examples_the_task_names() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    assert_eq!(
        phonemize(&phonemizer, "你好世界123").phonemes,
        "ni↗xau↓ ʂɻ̩↘ʨje↘ i↘pai↓ɚ↘ʂɻ̩↗ sa→n"
    );

    assert_eq!(
        phonemize(&phonemizer, "中文ABC英文").phonemes,
        format!(
            "{}{}{}",
            phonemize(&phonemizer, "中文").phonemes,
            phonemize(&phonemizer, "ABC").phonemes,
            phonemize(&phonemizer, "英文").phonemes
        )
    );
}

/// Every corpus sample the phase 9D tone rules move, and what they move it to.
///
/// One entry per sample, grouped by the rule that did it. The values are the
/// shipped pipeline's, and the point of the table is that
/// `the_tone_rules_change_exactly_these_samples` reads it from both directions:
/// each entry must differ from the JavaScript and match its new value, and every
/// sample *not* in the table must be identical under both pipelines. Adding
/// sandhi somewhere new — or breaking it somewhere old — fails there.
///
/// The rules, in the order the entries appear:
///
/// - **三声连读** — 你好 is *ní hǎo*, and 我有 and 处理 and 所以 and 一百个 lose
///   their third tone the same way.
/// - **轻声** — 一个 is *yí ge*, and the 的 of 这个项目的… is the particle and not
///   the 的 of 目的, which is what `pinyin-pro` reads it as on its own.
/// - **合词** — 不做 and 一四 and 处理 are one word after the merge pass, which is
///   why a space disappears: `3.14` is 三点一四 and 一四 is one word to the
///   reference, so `i→sɹ̩↘` has no space in it where the JavaScript had one.
const TONE_RULE_CHANGES: &[(&str, &str)] = &[
    // 三声连读
    ("你好世界", "ni↗xau↓ ʂɻ̩↘ʨje↘"),
    ("你好世界123", "ni↗xau↓ ʂɻ̩↘ʨje↘ i↘pai↓ɚ↘ʂɻ̩↗ sa→n"),
    ("你好，世界。", "ni↗xau↓. ʂɻ̩↘ʨje↘."),
    ("你好 世界", "ni↗xau↓ ʂɻ̩↘ʨje↘"),
    ("你好   世界", "ni↗xau↓ ʂɻ̩↘ʨje↘"),
    ("你好　世界", "ni↗xau↓ ʂɻ̩↘ʨje↘"),
    ("  你好世界  ", "ni↗xau↓ ʂɻ̩↘ʨje↘"),
    ("你好あ世界", "ni↗xau↓ʂɻ̩↘ʨje↘"),
    ("我有3只猫", "wo↗jou↓ sa→nꭧɻ̩→ mau→"),
    // 轻声
    ("我们中出了一个叛徒", "wo↓mən ꭧʊ→ŋꭧʰu→ lɤ i↗kɤ pʰa↘ntʰu↗"),
    (
        "这个项目的性能优化还有很大空间",
        "ꭧɤ↘kɤ ɕja↘ŋmu↘ ti ɕi↘ŋnə↗ŋ jou→xwa↘ xai↗jou↓ xə↓nta↘ kʰʊ→ŋʨjɛ→n",
    ),
    // 合词, plus the 轻声 and 三声连读 in the same sentence
    ("3.14", "sa→ntjɛ↓n i→sɹ̩↘"),
    (
        "他是一个非常努力的学生每天早上六点起床跑步然后去图书馆学习到晚上十点才回家休息",
        "tʰa→ ʂɻ̩↘ i↗kɤ fei→ꭧʰa↗ŋ nu↓li↘ tɤ ɕɥe↗ʂə→ŋ mei↓tʰjɛ→n ʦau↓ʂa↘ŋ ljou↘tjɛ↓n ʨʰi↓ꭧʰwa↗ŋ pʰau↓pu↘ ɻa↗nxou↘ ʨʰy↘ tʰu↗ʂu→kwa↓n ɕɥe↗ɕi↗ tau↘ wa↓nʂa↘ŋ ʂɻ̩↗tjɛ↓n ʦʰai↗ xwei↗ʨja→ ɕjou→ɕi",
    ),
    (
        "这段话的长度超过了一百个字符所以它会被用来检验分词算法在概率相乘时的处理方式因为如果不做处理的话所有的候选分词方案的乘积都会下溢为零从而无法比较",
        "ꭧɤ↘twa↘nxwa↘ tɤ ꭧʰa↗ŋtu↘ ꭧʰau→kwo↘ lɤ i↘pai↓kɤ ʦɹ̩↘fu↗ swo↗i↓ tʰa→xwei↘ pei↘ jʊ↘ŋlai↗ ʨjɛ↓njɛ↘n fə→nʦʰɹ̩↗ swa↘nfa↓ ʦai↘ kai↘ly↘ ɕja→ŋꭧʰə↗ŋ ʂɻ̩↗ tɤ ꭧʰu↗li↓ fa→ŋʂɻ̩↘ i→nwei↘ ɻu↗kwo↓ pu↗ʦwo↘ ꭧʰu↗li↓ tɤxwa↘ swo↗jou↓ tɤ xou↘ɕɥɛ↓n fə→nʦʰɹ̩↗ fa→ŋa↘n tɤ ꭧʰə↗ŋʨi→ tou→ xwei↘ ɕja↘i↘ wei↘ li↗ŋ ʦʰʊ↗ŋɚ↗ u↗fa↓ pi↓ʨjau↘",
    ),
];

/// The shipped pipeline against the corpus, sample by sample, and the claim that
/// the tone rules are the *only* difference from the phase 6 pipeline.
///
/// **Tone rules only**: both sides of this comparison run with no text
/// normalizer, so the phase 9E numeral step cannot show up here as a "tone rule
/// change". That decomposition is what lets the table below be read as a claim
/// about one mechanism — `the_text_normalizer_changes_exactly_these_samples` is
/// the same test for the other one.
///
/// Asserted from both directions on purpose. A list of changed samples would pass
/// if a later change moved a *third* sample and rewrote the corpus; the `None`
/// arm — every sample not in the table has to come out identical under both
/// pipelines *and* identical to the JavaScript — is what makes the table a
/// complete description of the difference rather than a record of part of it.
#[test]
fn the_tone_rules_change_exactly_these_samples() {
    let Some(legacy) = legacy() else {
        return;
    };

    let samples = corpus().samples;
    let mut seen = 0;
    for sample in &samples {
        let shipped = legacy.phonemes(&sample.input, ToneRules::On, None);
        let before = legacy.phase6(&sample.input);
        assert_eq!(
            before, sample.js,
            "{:?}: the phase 6 pipeline is the corpus",
            sample.input
        );

        match TONE_RULE_CHANGES
            .iter()
            .find(|(input, _)| *input == sample.input)
        {
            Some((_, expected)) => {
                seen += 1;
                assert_eq!(
                    shipped, *expected,
                    "{:?} under the tone rules",
                    sample.input
                );
                assert_ne!(
                    shipped, before,
                    "{:?} is in the table but did not move",
                    sample.input
                );
            }
            None => assert_eq!(
                shipped, before,
                "{:?} is not in the table but the tone rules moved it",
                sample.input
            ),
        }
    }

    // And the table does not describe samples the corpus does not have.
    assert_eq!(
        seen,
        TONE_RULE_CHANGES.len(),
        "every entry in the table is a corpus sample"
    );
}

/// Every corpus sample the phase 9E numeral step moves, and what it moves it to.
///
/// The same shape as [`TONE_RULE_CHANGES`], and deliberately separate from it:
/// this table is about the *numeral* step and the other one is about the tone
/// rules, so a regression in one cannot hide behind a pin in the other. Both are
/// read from both directions — each entry must differ from the pipeline without
/// the normalizer and match its new value, and every sample *not* in the table
/// must be identical with and without it.
///
/// Five of forty-seven samples move, and the forty-two that do not are the
/// reassuring half: `123`, `123.45`, `50%`, `100015`, `15％` and `我有3只猫` all
/// come out the same either way, because for a bare cardinal the two readers
/// agree. What moves is what has *context* to read.
///
/// Per entry, in order:
///
/// - **`第 3 季度…` — a space.** `第 3 季度` is one entity to the grammar and two
///   runs to `numbers_to_han`, so the space between 三 and 季度 goes. Cosmetic,
///   and the direction is towards how the sentence is actually said.
/// - **`1.2.3` — neither reading means anything.** `numbers_to_han`'s four
///   chained patterns give 一点二.三; the tagger fragments it at the first dot
///   and gives 一.二点三. This is a malformed number and both answers are
///   arbitrary; what matters is that it is *pinned* rather than discovered.
/// - **`０１２３` — this one is worse, and it is the reference's behaviour.** The
///   tagger splits it into `math{0}` and `math{123}`, so it reads 零一百二十三
///   where `numbers_to_han` strips the leading zero and says 一百二十三. That is
///   what `pip install wetext==0.1.8` produces for the same input, so it is not a
///   defect in this copy — it is a cost of the switch, recorded here so nobody
///   finds it by listening. (`007` goes the other way: the grammar says 零零七,
///   which is how a code is read and how the hand-written reader did not.)
/// - **`２０２２年` — the headline improvement.** A year is read as a year:
///   二零二二年, not 二千零二十二年. `numbers_to_han` has no context to tell a year
///   from a quantity and reads both as quantities; this is the class of input the
///   engine was wired up for.
/// - **`1,234` — 两 for 二.** Both readers keep the comma and read only the last
///   group, so both are wrong; the grammar says 两百 where the hand-written
///   reader said 二百, and 两百 is the form the user asked for (see the 9B
///   decision note). The space before 三十四 goes for the same reason as the
///   first entry.
const TEXT_NORMALIZER_CHANGES: &[(&str, &str)] = &[
    (
        "第 3 季度营收增长了 15.6%。",
        "ti↘ sa→nʨi↘tu↘ i↗ŋʂou→ ʦə→ŋꭧa↓ŋ lɤ pai↓fə→nꭧɻ\u{329}→ʂɻ\u{329}↗u↓ tjɛ↓nljou↘.",
    ),
    ("1.2.3", "i→.ɚ↘tjɛ↓n sa→n"),
    ("０１２３", "li↗ŋ i→pai↓ɚ↘ʂɻ\u{329}↗ sa→n"),
    ("２０２２年", "ɚ↘li↗ŋɚ↘ ɚ↘njɛ↗n"),
    ("1,234", "i→,lja↗ŋpai↓ sa→nʂɻ\u{329}↗sɹ\u{329}↘"),
];

/// The shipped pipeline against the corpus, sample by sample, with the numeral
/// step as the only difference.
#[test]
fn the_text_normalizer_changes_exactly_these_samples() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };
    let Some(legacy) = legacy() else {
        return;
    };

    let samples = corpus().samples;
    let mut seen = 0;
    for sample in &samples {
        let shipped = phonemize(&phonemizer, &sample.input).phonemes;
        let without = legacy.phonemes(&sample.input, ToneRules::On, None);

        match TEXT_NORMALIZER_CHANGES
            .iter()
            .find(|(input, _)| *input == sample.input)
        {
            Some((_, expected)) => {
                seen += 1;
                assert_eq!(shipped, *expected, "{:?} with WeText", sample.input);
                assert_ne!(
                    shipped, without,
                    "{:?} is in the table but did not move",
                    sample.input
                );
            }
            None => assert_eq!(
                shipped, without,
                "{:?} is not in the table but the numeral step moved it",
                sample.input
            ),
        }
    }

    assert_eq!(
        seen,
        TEXT_NORMALIZER_CHANGES.len(),
        "every entry in the table is a corpus sample"
    );
}

#[test]
fn puts_one_space_between_words_and_none_inside_them() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // The user's report, and the reason jieba is in the pipeline at all: 人设
    // and 曾经 are each one word, and the model paused between their characters
    // when every syllable was separated. One word means one unit means no
    // boundary — so this is two spaces in the whole string, not five.
    let phonemes = phonemize(&phonemizer, "人设曾经").phonemes;
    assert_eq!(phonemes, "ɻə↗nʂɤ↘ ʦʰə↗ŋʨi→ŋ");
    assert_eq!(phonemes.matches(' ').count(), 1);

    // And the boundaries are jieba's, not a syllable count: 中华人民共和国 is
    // one word here, so the space after it is the only one in the first half.
    assert_eq!(
        phonemize(&phonemizer, "中华人民共和国武汉市长江大桥").phonemes,
        "ꭧʊ→ŋxwa↗ɻə↗nmi↗nkʊ↘ŋxɤ↗kwo↗ u↓xa↘nʂɻ̩↘ ꭧa↓ŋʨja→ŋta↘ʨʰjau↗"
    );
}

#[test]
fn a_latin_run_leaves_the_han_around_it_alone() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // The contract, and the property that survives the two sides using different
    // English engines: the runs are concatenated with nothing inserted, so the
    // whole is exactly its parts in order. Asserted by building the expected
    // string out of three separate calls rather than by writing it down, so the
    // test says "the Han is unaffected" rather than pinning whatever the English
    // engine happened to produce this month.
    let mixed = phonemize(&phonemizer, "你好ABC世界").phonemes;
    let expected = format!(
        "{}{}{}",
        phonemize(&phonemizer, "你好").phonemes,
        phonemize(&phonemizer, "ABC").phonemes,
        phonemize(&phonemizer, "世界").phonemes
    );
    assert_eq!(mixed, expected);

    // The Latin part really is the English engine's, and not the letters passed
    // through: an initialism is spelled out, and the schwa for `A` is CMU Dict's
    // entry for the letter — which is what `en_g2p.rs` pins as phase 4's answer,
    // and what espeak would have answered differently.
    assert_eq!(phonemize(&phonemizer, "ABC").phonemes, "ə bˈiː sˈiː");

    // A mixed-case word is read as a word, not spelled.
    assert!(phonemize(&phonemizer, "Hello世界")
        .phonemes
        .starts_with("həlˈoʊ"));
}

#[test]
fn a_numerals_reading_is_not_a_separate_run() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // The numeral has to become Han *before* the runs are split, or it would land
    // in an `other` run and be dropped as punctuation — unheard, and silently.
    // 只 is what makes this visible: as 三只 it is read with the numeral in one
    // word, and a split run would leave 三 missing and the word boundary wrong.
    // 我有 is two third tones in a row and the merge pass makes it one word, so
    // the shipped pipeline says *wó yǒu*: `wo↗jou↓` where the JavaScript said
    // `wo↓ jou↓`.
    assert_eq!(
        phonemize(&phonemizer, "我有3只猫").phonemes,
        "wo↗jou↓ sa→nꭧɻ̩→ mau→"
    );

    // And the reading itself, so a failure says which half broke.
    assert_eq!(phonemize(&phonemizer, "123").phonemes, "i↘pai↓ɚ↘ʂɻ̩↗ sa→n");
    assert_eq!(
        phonemize(&phonemizer, "123.45").phonemes,
        "i↘pai↓ɚ↘ʂɻ̩↗ sa→ntjɛ↓n sɹ̩↘u↓"
    );
}

#[test]
fn a_run_this_frontend_cannot_read_is_dropped_rather_than_read_wrong() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // Kana is `other` to `chinese.ts` — it has no kana alternative in its run
    // pattern — and `keepPunctuation` has no kana in its set, so it is dropped.
    // Reading it with the Chinese syllable table would be worse than dropping it,
    // which is why the Chinese pipeline has no kana run at all.
    //
    // **Dropping it also costs the word boundary**, and that is not a bug in
    // either implementation: 你好 and 世界 are two Han runs with an unreadable run
    // between them, and jieba segments each run on its own — so the space that
    // `你好世界` gets from being one two-word run does not appear. Asserted as the
    // concatenation rather than as the fixed string so the test says which
    // property is being checked, and pinned against the JavaScript by the corpus.
    assert_eq!(
        phonemize(&phonemizer, "你好あ世界").phonemes,
        format!(
            "{}{}",
            phonemize(&phonemizer, "你好").phonemes,
            phonemize(&phonemizer, "世界").phonemes
        )
    );
}

#[test]
fn refuses_a_character_pinyin_pro_cannot_read() {
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    // U+3400 is in the Han range and absent from the dictionary. Returning the
    // rest of the sentence — as the verification script did — drops the character
    // from the audio without a trace, and a sentence missing a word sounds like a
    // sentence.
    let error = phonemizer
        .phonemize_with("你好㐀", &chinese_options())
        .expect_err("㐀 has no reading");

    assert_eq!(error.code(), "unreadable-characters");
    assert!(matches!(error, PhonemizeError::Pipeline(_)));
}

#[test]
fn refuses_to_phonemize_before_the_dictionary_arrived() {
    // A fresh instance has no segmenter, and a sentence read without word
    // boundaries is audible (人设, 曾经) — so this is a failure rather than a
    // sentence that comes out with the wrong spacing.
    let phonemizer = Phonemizer::new();

    let error = phonemizer
        .phonemize_with("你好世界", &chinese_options())
        .expect_err("nothing was prepared");

    assert_eq!(error.code(), "dictionary-not-loaded");
    assert!(matches!(error, PhonemizeError::NotPrepared { .. }));
}

#[test]
fn every_corpus_sample_passes_the_vocabulary_gate() {
    // Implicit in `phonemize_with`, which validates before returning — but
    // asserted separately because the gate is the thing that turns "a character
    // the tokenizer would silently delete" into a failure, and a corpus is the
    // cheapest way to check it across a lot of input at once. If this ever fails
    // it will fail inside `phonemize` above first; the point of having it twice is
    // that the reason is in the message.
    let Some(phonemizer) = chinese_phonemizer() else {
        return;
    };

    for sample in corpus().samples {
        let result = phonemizer.phonemize_with(&sample.input, &chinese_options());
        assert!(
            result.is_ok(),
            "{:?} failed the gate: {}",
            sample.input,
            result.expect_err("checked")
        );
    }
}

/// What the phase 9E numeral step buys, at the phoneme level.
///
/// The corpus table above says which *corpus* samples move; this one says what
/// the engine reads that the corpus does not cover, with both sides pinned so a
/// failure identifies which of the two readers changed. Every row is a class the
/// hand-written reader has no rule for — a clock time with a colon in it, a
/// currency sign, a fraction, a phone number — except the first two, which are
/// here because they show the same change is not local to a bare numeral.
///
/// Two rows read *worse* and are pinned anyway: `2,000` as 二,零零零 against
/// 二,零, and the 减 of `555-1234`. Neither old reading was usable either, and a
/// table of only the improvements would be a table that could not fail.
#[test]
fn the_numeral_step_reads_these_entities() {
    let Some(legacy) = legacy() else {
        return;
    };
    let Some(tn) = common::chinese_tn() else {
        return;
    };

    let table: &[(&str, &str, &str)] = &[
        (
            "今天是2024年10月4日",
            "ʨi→ntʰjɛ→n ʂɻ\u{329}↘ ɚ↘li↗ŋɚ↘ sɹ\u{329}↘njɛ↗n ʂɻ\u{329}↗ɥe↘ sɹ\u{329}↘ɻɻ\u{329}↘",
            "ʨi→ntʰjɛ→n ʂɻ\u{329}↘ ɚ↘ʨʰjɛ→n li↗ŋ ɚ↘ʂɻ\u{329}↗sɹ\u{329}↘njɛ↗n ʂɻ\u{329}↗ɥe↘ sɹ\u{329}↘ɻɻ\u{329}↘",
        ),
        (
            "2024年",
            "ɚ↘li↗ŋɚ↘ sɹ\u{329}↘njɛ↗n",
            "ɚ↘ʨʰjɛ→n li↗ŋ ɚ↘ʂɻ\u{329}↗sɹ\u{329}↘njɛ↗n",
        ),
        (
            "1,234个",
            "i↘ʨʰjɛ→nɚ↘pai↓ sa→nʂɻ\u{329}↗sɹ\u{329}↘kɤ",
            "i→,ɚ↘pai↓sa→nʂɻ\u{329}↗ sɹ\u{329}↘kɤ",
        ),
        ("200元", "lja↗ŋpai↓ɥɛ↗n", "ɚ↘pai↓ɥɛ↗n"),
        // The colon used to survive into the output and be kept as punctuation.
        (
            "下午3:30",
            "ɕja↘u↓ sa→ntjɛ↓n sa→nʂɻ\u{329}↗fə→n",
            "ɕja↘u↓ sa→n:sa→nʂɻ\u{329}↗",
        ),
        // The currency sign was dropped by the punctuation filter, so nothing
        // said what the number was.
        (
            "$20.50",
            "ɚ↘ʂɻ\u{329}↗tjɛ↓n u↓li↗ŋ mei↓ɥɛ↗n",
            "$ɚ↘ʂɻ\u{329}↗tjɛ↓n u↓li↗ŋ",
        ),
        ("1/2", "ɚ↘fə→nꭧɻ\u{329}→i→", "i→ɚ↘"),
        // Reads the 减 the grammar inserts for a hyphen. Old and new are both
        // wrong; the new one adds a word.
        (
            "电话是555-1234",
            "tjɛ↘nxwa↘ ʂɻ\u{329}↘ u↗pai↓ u↓ʂɻ\u{329}↗u↓ ʨjɛ↓n i↘ʨʰjɛ→nɚ↘pai↓ sa→nʂɻ\u{329}↗sɹ\u{329}↘",
            "tjɛ↘nxwa↘ ʂɻ\u{329}↘ u↗pai↓ u↓ʂɻ\u{329}↗u↓i↘ʨʰjɛ→nɚ↘pai↓ sa→nʂɻ\u{329}↗sɹ\u{329}↘",
        ),
        // The clearest win of the set: a phone number read digit by digit rather
        // than as three concatenated quantities.
        (
            "电话番号是090-1234-5678",
            "tjɛ↘nxwa↘ fa→nxau↘ ʂɻ\u{329}↘ li↗ŋ ʨjou↓li↗ŋ i→ɚ↘sa→nsɹ\u{329}↘u↓ ljou↘ ʨʰi→pa→",
            "tjɛ↘nxwa↘ fa→nxau↘ ʂɻ\u{329}↘ ʨjou↓ʂɻ\u{329}↗i↘ʨʰjɛ→nɚ↘pai↓ sa→nʂɻ\u{329}↗sɹ\u{329}↘u↓ʨʰjɛ→n ljou↘pai↓ ʨʰi→ʂɻ\u{329}↗pa→",
        ),
        (
            "第3季度营收10,000,000元。",
            "ti↘sa→nʨi↘tu↘ i↗ŋʂou→ i↘ʨʰjɛ→nwa↘nɥɛ↗n.",
            "ti↘sa→nʨi↘tu↘ i↗ŋʂou→ʂɻ\u{329}↗,li↗ŋ,li↗ŋɥɛ↗n.",
        ),
    ];

    for (input, with, without) in table {
        assert_eq!(
            legacy.phonemes(input, ToneRules::On, None),
            *without,
            "{input:?} without the numeral step"
        );
        assert_eq!(
            legacy.phonemes(input, ToneRules::On, Some(&tn)),
            *with,
            "{input:?} with WeText"
        );
        assert_ne!(with, without, "{input:?} is in the table but did not move");
    }
}
